print("Catálogo de séries Netflix:")
print("Dark")
print("Stranger Things")
print("Suits")
print("Vikings")
print("Sex Education")
print("Sandman")
print("Peaky Blinders")
print("Kingdom")
print("Resident Evil")
print("The OA")
